# Site settings
title: brickwokers` home
description: A blog about source learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.brickworkers.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brickworker
user_description: Anon Developer at JAVA、GO
email: 297988405@qq.com
twitter_username: none
github_username:  BrickWorker
gplus_username:  none
disqus_username: none

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主页
    url: /
  - title: 系列文章
    url: /series
  - title: 标签
    url: /tags
  - title: 关于我
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
